name: conchayoro-pipeline
on:
 push:
    branches: [ "main" ]
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v3
  - name: setup node
    uses: actions/setup-node@v3
    with:
     node-version: '18'
     cache: 'npm'
  - name: Build and Test
    run: npm install
  - name: build
    run: npm run build
 deploy_homologation:
  runs-on: ubuntu-latest
  needs: build
  steps:
  - uses: actions/download-artifact@v3
    with:
     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
     AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
     AWS_EC2_METADATA_DISABLED: true
     BUCKET_S3: ${{ vars.BUCKET_S3 }}
  - name: Upload to Homologacao Bucket
  - run: aws s3 cp frontend/.next/server/app s3://$BUCKET_S3 --recursive --acl public-read
 deploy_producao:
    needs: build
    runs-on: ubuntu-latest

    if: contains(github.event.head_commit.message, 'texto-especifico-no-commit')

    steps:
    - name: Manual Deploy to Producao
      uses: wei/github-actions-deploy-digitalocean@v1
      with:
       token: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
 deploy_producao_manual:
     needs: deploy_producao
     runs-on: ubuntu-latest
     steps:
     - name: Manual Approval
       uses: wei/github-actions-approval@v1
